# Generated by Django 5.0.3 on 2024-03-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendWork', '0002_alter_invoice_orderstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='orderStatus',
            field=models.CharField(choices=[('C1', 'Cart'), ('C2', 'Completed')], max_length=2),
        ),
    ]
